### PR TITLE
Update website Feb 2017

### PR DESCRIPTION
**Pull request by abigailStev**
Added section on how to get involved (including a link to GSoC 2017
project ideas page), added the logo to the website, mentioned Slack and
mailing list, tinkered with phrasing.

### CODE REVIEW

**Comment by abigailStev** [comment]
ping @matteobachetti @dhuppenkothen

**Comment by matteobachetti** [comment]
Hey Abby! Thanks for thinking about this!
Could you take the chance to add an acknowledgement to Jetbrains for the free use of PyCharm using [one of their logos](http://www.jetbrains.com/company/press/materials.html)?

**Comment by matteobachetti** [comment]
I'll do the same in the README

**Comment by abigailStev** [comment]
@matteobachetti Sure!

**Comment by matteobachetti** [comment]
Good for me. Merge when you are done with the last mods. We can always add/change things later

**Pull request merged**
